name: Scan GitHub repository
on: push

jobs:
  scan-github-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mondoohq/actions/k8s@v0.9.3
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_CONFIG_BASE64 }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          repository: ${{ GITHUB_REPOSITORY }}
